[package]
name = "edr_test_utils"
version = "0.1.0-dev"
edition = "2021"

[dependencies]
edr_defaults = { version = "0.1.0-dev", path = "../edr_defaults" }
serde = { version = "1.0.147", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.89" }
tempfile = "3.7.1"
